# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.java.installations.auto-download=true
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.1.2
loader_version=0.19.2
loom_version=1.16-SNAPSHOT
# Mod Properties
mod_version=1.0.11
maven_group=com.spider
archives_base_name=framedfabric-2
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_api_version=0.146.1+26.1.2
jei_version=29.16.0.47
